### ISSUE TITLE
Broken link for creating a model in WKS

### ISSUE THREAD

**Issue by scottdangelo** [IBM/gdpr-fingerprint-pii#1]
The link for step #4 is broken. This does not work:
```
https://github.ibm.com/IBMCode/howtos/tree/master/extracting-personal-data-from-unstructured-text-using-watson-knowledge-studio
```

**Comment by muralidharchavan** [comment]
The link will be available once the PR for the how-to is merged with master branch. Meanwhile, may I ask you to refer to the branch from where it will be merged please? branch code to be merged is "https://github.ibm.com/muralidhar-chavan/howtos/tree/gdpr-wks/extracting-personal-data-from-unstructured-text-using-watson-knowledge-studio".

**Comment by muralidharchavan** [comment]
Hi @scottdangelo 
I assume you are unable to continue validating this pattern because the reference to how-to is broken. I have created a PR for adding content of the how-to to this pattern. @stevemart suggested that the PR be open so that you can continue validating this pattern. Can you continue validating this pattern using the open PR https://github.com/IBM/gdpr-fingerprint-pii/pull/4 please? If there's any concern please let me know. Thanks
